import os
import re
import subprocess
from datetime import datetime
from anthropic import Anthropic

MODEL = "claude-sonnet-4-5-20250929"
MAX_ITERS = 4

def sh(cmd: list[str], check=True):
    return subprocess.run(cmd, check=check, text=True, capture_output=True)

def safe_branch_name(task: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", task.strip().lower())[:40].strip("-")
    ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    return f"claude/{ts}-{slug or 'task'}"

def repo_context() -> str:
    files = sh(["bash", "-lc", "git ls-files | head -n 200"]).stdout
    ctx = ["Repository file list (first 200):", files]
    for p in ["README.md", "requirements.txt"]:
        if os.path.exists(p):
            content = open(p, "r", encoding="utf-8", errors="ignore").read()
            ctx.append(f"\n--- {p} ---\n" + content[:4000])
    return "\n".join(ctx)

def ask_claude_for_diff(client: Anthropic, task: str, ctx: str, feedback: str = "") -> str:
    system = (
        "You are a senior software engineer.\n"
        "Output ONLY a unified diff that can be applied with `git apply`.\n"
        "Do not include explanations, markdown, or extra text.\n"
        "Make the smallest correct change.\n"
    )
    user = f"""TASK:
{task}

CONTEXT:
{ctx}

FEEDBACK (if any):
{feedback}

Remember: output ONLY a unified diff (git apply compatible).
"""
    msg = client.messages.create(
        model=MODEL,
        max_tokens=4000,
        messages=[{"role": "user", "content": user}],
        system=system,
    )
    return msg.content[0].text

def apply_diff(diff_text: str) -> str:
    patch_path = "claude.patch"
    open(patch_path, "w", encoding="utf-8").write(diff_text)
    proc = sh(["bash", "-lc", f"git apply --whitespace=fix {patch_path}"], check=False)
    if proc.returncode != 0:
        return f"git apply failed:\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}\n"
    return ""

def run_checks() -> str:
    cmds = [
        "python -m compileall -q .",
        "pytest -q",
    ]
    out = []
    for c in cmds:
        proc = sh(["bash", "-lc", c], check=False)
        out.append(f"$ {c}\nRET={proc.returncode}\n{proc.stdout}\n{proc.stderr}\n")
        if proc.returncode != 0:
            return "\n".join(out)
    return ""

def main():
    task = os.environ.get("TASK", "").strip()
    if not task:
        raise SystemExit("TASK env is required")

    client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    base_branch = sh(["bash", "-lc", "git rev-parse --abbrev-ref HEAD"]).stdout.strip()
    branch = safe_branch_name(task)

    sh(["bash", "-lc", f"git checkout -b {branch}"])
    ctx = repo_context()

    feedback = ""
    for i in range(1, MAX_ITERS + 1):
        diff = ask_claude_for_diff(client, task, ctx, feedback)
        err = apply_diff(diff)
        if err:
            feedback = f"Attempt {i}: diff could not be applied.\n{err}"
            sh(["bash", "-lc", "git reset --hard"])
            continue

        checks = run_checks()
        if checks:
            feedback = f"Attempt {i}: tests/checks failed.\n{checks}"
            sh(["bash", "-lc", "git reset --hard"])
            continue

        sh(["bash", "-lc", "git add -A"])
        sh(["bash", "-lc", f'git commit -m "claude: {task[:72]}"'])
        sh(["bash", "-lc", f"git push -u origin {branch}"])

        pr_title = f"[Claude] {task[:80]}"
        pr_body = f"Auto-generated by Claude PR loop.\n\nTask:\n- {task}\n"
        sh(["bash", "-lc", f'gh pr create --base "{base_branch}" --head "{branch}" --title "{pr_title}" --body "{pr_body}"'])
        print("PR created.")
        return

    raise SystemExit(f"Failed after {MAX_ITERS} attempts.\nLast feedback:\n{feedback}")

if __name__ == "__main__":
    main()
